/* Screen Dream FFI — auto-generated by cbindgen. DO NOT EDIT. */

#ifndef SCREEN_DREAM_FFI_H
#define SCREEN_DREAM_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for an in-progress recording session.
 * The internal fields are not exposed across the FFI boundary.
 * The `inner` pointer is managed by the recording module.
 */
typedef struct SDRecordingHandle SDRecordingHandle;

/**
 * FFI error type.  Caller must free with `sd_free_error`.
 */
typedef struct SDError {
    char *kind;
    char *message;
} SDError;

typedef struct SDPlatformInfo {
    char *os;
    char *display_server;
    char *arch;
} SDPlatformInfo;

/**
 * FFmpeg availability and capabilities.
 * The `video_encoders_json` and `audio_encoders_json` fields contain JSON arrays
 * of encoder name strings for easy consumption in higher-level languages.
 */
typedef struct SDFfmpegStatus {
    bool available;
    char *version;
    char *source_description;
    char *video_encoders_json;
    char *audio_encoders_json;
} SDFfmpegStatus;

typedef struct SDMonitorInfo {
    uint32_t id;
    char *name;
    char *friendly_name;
    uint32_t width;
    uint32_t height;
    int32_t x;
    int32_t y;
    float scale_factor;
    bool is_primary;
} SDMonitorInfo;

typedef struct SDWindowInfo {
    uint32_t id;
    uint32_t pid;
    char *app_name;
    char *title;
    uint32_t width;
    uint32_t height;
    bool is_minimized;
    bool is_focused;
} SDWindowInfo;

typedef struct SDAvailableSources {
    struct SDMonitorInfo *monitors;
    uint32_t monitors_count;
    struct SDWindowInfo *windows;
    uint32_t windows_count;
    bool windows_unavailable;
    char *windows_unavailable_reason;
} SDAvailableSources;

/**
 * Raw captured frame data.
 */
typedef struct SDFrame {
    uint8_t *data;
    uint32_t data_len;
    uint32_t width;
    uint32_t height;
} SDFrame;

/**
 * C-compatible capture source descriptor.
 *
 * `source_type`: 0 = Screen, 1 = Window, 2 = Region.
 *
 * For Screen: only `monitor_id` is used.
 * For Window: only `window_id` is used.
 * For Region: `monitor_id`, `region_x`, `region_y`, `region_width`, `region_height` are used.
 */
typedef struct SDCaptureSource {
    uint32_t source_type;
    uint32_t monitor_id;
    uint32_t window_id;
    int32_t region_x;
    int32_t region_y;
    uint32_t region_width;
    uint32_t region_height;
} SDCaptureSource;

/**
 * Configuration for starting a recording session.
 * String fields are borrowed (`*const c_char`) -- the caller retains ownership.
 */
typedef struct SDRecordingConfig {
    struct SDCaptureSource source;
    uint32_t fps;
    const char *video_codec;
    uint8_t crf;
    const char *preset;
    const char *output_path;
    bool capture_microphone;
    const char *microphone_device;
} SDRecordingConfig;

/**
 * Recording status update.
 *
 * `state`: 0=Idle, 1=Starting, 2=Recording, 3=Paused, 4=Stopping, 5=Completed, 6=Failed.
 */
typedef struct SDRecordingStatus {
    uint32_t state;
    double elapsed_seconds;
    uint64_t frames_captured;
} SDRecordingStatus;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the Screen Dream core.
 *
 * `config_dir` — NUL-terminated path to the configuration directory
 *                (e.g. `~/.config/screen-dream`).  The directory will be
 *                created if it does not exist.
 *
 * On success returns `true` and leaves `*error` unchanged.
 * On failure returns `false` and writes a heap-allocated `SDError` into `*error`.
 * The caller must free it with `sd_free_error`.
 *
 * Calling `sd_init` more than once (without `sd_shutdown`) is a no-op that returns `true`.
 *
 * # Safety
 * * `config_dir` must be a valid NUL-terminated UTF-8 string.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
bool sd_init(const char *config_dir, struct SDError **error);

/**
 * Shut down the Screen Dream core and release all resources.
 *
 * After calling this, `sd_init` may be called again.
 *
 * # Safety
 * No other FFI calls may be in flight when this is called.
 */
void sd_shutdown(void);

/**
 * Free a string allocated by the Rust FFI layer.
 *
 * # Safety
 * `s` must have been returned by a Screen Dream FFI function, or be null.
 */
void sd_free_string(char *s);

/**
 * Free an `SDError` allocated by the Rust FFI layer.
 *
 * # Safety
 * `e` must have been returned by a Screen Dream FFI function, or be null.
 */
void sd_free_error(struct SDError *e);

/**
 * Returns platform information (OS, display server, architecture).
 *
 * The returned struct contains heap-allocated strings. The caller must
 * free each string field with `sd_free_string` when done.
 *
 * # Safety
 * `sd_init` must have been called successfully before calling this function.
 */
struct SDPlatformInfo sd_get_platform_info(void);

/**
 * Query FFmpeg availability and capabilities.
 *
 * On success returns a heap-allocated `SDFfmpegStatus`. The caller must
 * free it with `sd_free_ffmpeg_status`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `sd_init` must have been called successfully.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
struct SDFfmpegStatus *sd_get_ffmpeg_status(struct SDError **error);

/**
 * Free an `SDFfmpegStatus` returned by `sd_get_ffmpeg_status`.
 *
 * # Safety
 * `status` must have been returned by `sd_get_ffmpeg_status`, or be null.
 */
void sd_free_ffmpeg_status(struct SDFfmpegStatus *status);

/**
 * Load application settings and return them as a JSON string.
 *
 * On success returns a heap-allocated NUL-terminated JSON string.
 * The caller must free it with `sd_free_string`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `sd_init` must have been called successfully.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
char *sd_load_settings(struct SDError **error);

/**
 * Save application settings from a JSON string.
 *
 * On success returns `true`. On failure sets `*error` and returns `false`.
 *
 * # Safety
 * * `json` must be a valid NUL-terminated UTF-8 string.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
bool sd_save_settings(const char *json, struct SDError **error);

/**
 * Reset settings to defaults and return the new defaults as a JSON string.
 *
 * On success returns a heap-allocated NUL-terminated JSON string.
 * The caller must free it with `sd_free_string`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `sd_init` must have been called successfully.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
char *sd_reset_settings(struct SDError **error);

/**
 * Enumerate all available capture sources (monitors and windows).
 *
 * On success returns a heap-allocated `SDAvailableSources`. The caller
 * must free it with `sd_free_available_sources`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `sd_init` must have been called successfully.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
struct SDAvailableSources *sd_enumerate_sources(struct SDError **error);

/**
 * Free an `SDAvailableSources` returned by `sd_enumerate_sources`.
 *
 * # Safety
 * `sources` must have been returned by `sd_enumerate_sources`, or be null.
 */
void sd_free_available_sources(struct SDAvailableSources *sources);

/**
 * Capture a single frame from the given source.
 *
 * On success returns a heap-allocated `SDFrame` containing raw RGBA pixel data.
 * The caller must free it with `sd_free_frame`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `source` must be a valid pointer to an `SDCaptureSource`.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
struct SDFrame *sd_capture_frame(const struct SDCaptureSource *source, struct SDError **error);

/**
 * Free an `SDFrame` returned by `sd_capture_frame`.
 *
 * # Safety
 * `frame` must have been returned by `sd_capture_frame`, or be null.
 */
void sd_free_frame(struct SDFrame *frame);

/**
 * Capture a screenshot and save it to a file.
 *
 * The output format is determined by the file extension (`.png`, `.jpg`, `.webp`).
 *
 * On success returns `true`. On failure sets `*error` and returns `false`.
 *
 * # Safety
 * * `source` must be a valid pointer to an `SDCaptureSource`.
 * * `output_path` must be a valid NUL-terminated UTF-8 string.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
bool sd_take_screenshot(const struct SDCaptureSource *source,
                        const char *output_path,
                        struct SDError **error);

/**
 * Capture a screenshot and return it as a base64-encoded PNG string.
 *
 * On success returns a heap-allocated NUL-terminated string.
 * The caller must free it with `sd_free_string`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `source` must be a valid pointer to an `SDCaptureSource`.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
char *sd_take_screenshot_base64(const struct SDCaptureSource *source, struct SDError **error);

/**
 * Start a recording session.
 *
 * Takes a recording configuration and returns an opaque handle.
 * The caller must eventually call `sd_stop_recording` or `sd_free_recording_handle`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `config` must be a valid pointer to an `SDRecordingConfig`.
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
struct SDRecordingHandle *sd_start_recording(const struct SDRecordingConfig *config,
                                             struct SDError **error);

/**
 * Stop a recording and get the final output file path.
 *
 * If audio was captured, the video and audio are muxed together using FFmpeg.
 * The final path is written to `*out_path` (caller must free with `sd_free_string`).
 *
 * On success returns `true`. On failure sets `*error` and returns `false`.
 *
 * # Safety
 * * `handle` must have been returned by `sd_start_recording`.
 * * `out_path` must be a valid pointer to a `*mut c_char` (may point to null).
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
bool sd_stop_recording(struct SDRecordingHandle *handle, char **out_path, struct SDError **error);

/**
 * Pause an active recording.
 *
 * On success returns `true`. On failure sets `*error` and returns `false`.
 *
 * # Safety
 * `handle` must have been returned by `sd_start_recording` and not yet stopped.
 */
bool sd_pause_recording(struct SDRecordingHandle *handle, struct SDError **error);

/**
 * Resume a paused recording.
 *
 * On success returns `true`. On failure sets `*error` and returns `false`.
 *
 * # Safety
 * `handle` must have been returned by `sd_start_recording` and not yet stopped.
 */
bool sd_resume_recording(struct SDRecordingHandle *handle, struct SDError **error);

/**
 * Get the current status of a recording.
 *
 * Returns an `SDRecordingStatus` by value (no heap allocation).
 *
 * # Safety
 * `handle` must have been returned by `sd_start_recording`.
 */
struct SDRecordingStatus sd_get_recording_status(const struct SDRecordingHandle *handle);

/**
 * Free a recording handle.
 *
 * If the recording is still in progress, it will be stopped first.
 *
 * # Safety
 * `handle` must have been returned by `sd_start_recording`, or be null.
 */
void sd_free_recording_handle(struct SDRecordingHandle *handle);

/**
 * List available audio input devices as a JSON array.
 *
 * On success returns a heap-allocated NUL-terminated JSON string.
 * The caller must free it with `sd_free_string`.
 *
 * On failure sets `*error` and returns null.
 *
 * # Safety
 * * `error` must be a valid pointer to a `*mut SDError` (may point to null).
 */
char *sd_list_audio_devices(struct SDError **error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCREEN_DREAM_FFI_H */
